[package]
name = "nes-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"

sdl2 = "0.37.0"
rand = "=0.7.3"
serde = { version = "1.0.203", features = ["derive"] }

[build-dependencies]
cc = "1.0"